# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/inventory.proto\x12\x19\x63om.example.rpc.inventory\"8\n\x10InventoryRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\":\n\x11InventoryResponse\x12\x14\n\x0cis_available\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2{\n\x10InventoryService\x12g\n\nCheckStock\x12+.com.example.rpc.inventory.InventoryRequest\x1a,.com.example.rpc.inventory.InventoryResponseB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_INVENTORYREQUEST']._serialized_start=53
  _globals['_INVENTORYREQUEST']._serialized_end=109
  _globals['_INVENTORYRESPONSE']._serialized_start=111
  _globals['_INVENTORYRESPONSE']._serialized_end=169
  _globals['_INVENTORYSERVICE']._serialized_start=171
  _globals['_INVENTORYSERVICE']._serialized_end=294
# @@protoc_insertion_point(module_scope)
